[2025-05-16T18:47:38.134+0000] {logging_mixin.py:188} INFO - Changing /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-16T18:47:31.776515+00:00/task_id=merge_data permission to 509
[2025-05-16T18:47:38.134+0000] {logging_mixin.py:188} INFO - Failed to change /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-16T18:47:31.776515+00:00/task_id=merge_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-16T18:47:31.776515+00:00/task_id=merge_data'
[2025-05-16T18:47:38.154+0000] {logging_mixin.py:188} INFO - Changing /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-16T18:47:31.776515+00:00/task_id=merge_data permission to 509
[2025-05-16T18:47:38.155+0000] {logging_mixin.py:188} INFO - Failed to change /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-16T18:47:31.776515+00:00/task_id=merge_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-16T18:47:31.776515+00:00/task_id=merge_data'
[2025-05-16T18:47:38.183+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dimensional_model.merge_data manual__2025-05-16T18:47:31.776515+00:00 [queued]>
[2025-05-16T18:47:38.189+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dimensional_model.merge_data manual__2025-05-16T18:47:31.776515+00:00 [queued]>
[2025-05-16T18:47:38.189+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2025-05-16T18:47:38.199+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): merge_data> on 2025-05-16 18:47:31.776515+00:00
[2025-05-16T18:47:38.204+0000] {standard_task_runner.py:60} INFO - Started process 221 to run task
[2025-05-16T18:47:38.206+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'etl_dimensional_model', 'merge_data', 'manual__2025-05-16T18:47:31.776515+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/etl_load_postgres_dag.py', '--cfg-path', '/tmp/tmp9hyt833r']
[2025-05-16T18:47:38.207+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask merge_data
[2025-05-16T18:47:38.241+0000] {logging_mixin.py:188} INFO - Changing /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-16T18:47:31.776515+00:00/task_id=merge_data permission to 509
[2025-05-16T18:47:38.242+0000] {logging_mixin.py:188} INFO - Failed to change /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-16T18:47:31.776515+00:00/task_id=merge_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-16T18:47:31.776515+00:00/task_id=merge_data'
[2025-05-16T18:47:38.243+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_dimensional_model.merge_data manual__2025-05-16T18:47:31.776515+00:00 [running]> on host e3308f139649
[2025-05-16T18:47:38.398+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_dimensional_model' AIRFLOW_CTX_TASK_ID='merge_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-16T18:47:31.776515+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-16T18:47:31.776515+00:00'
[2025-05-16T18:47:53.663+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-16T18:47:53.673+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_dimensional_model, task_id=merge_data, execution_date=20250516T184731, start_date=20250516T184738, end_date=20250516T184753
[2025-05-16T18:47:53.717+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-16T18:47:53.735+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
