[2025-05-20T14:50:26.884+0000] {logging_mixin.py:188} INFO - Changing /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-20T14:50:19.910416+00:00/task_id=merge_data permission to 509
[2025-05-20T14:50:26.884+0000] {logging_mixin.py:188} INFO - Failed to change /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-20T14:50:19.910416+00:00/task_id=merge_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-20T14:50:19.910416+00:00/task_id=merge_data'
[2025-05-20T14:50:26.926+0000] {logging_mixin.py:188} INFO - Changing /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-20T14:50:19.910416+00:00/task_id=merge_data permission to 509
[2025-05-20T14:50:26.926+0000] {logging_mixin.py:188} INFO - Failed to change /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-20T14:50:19.910416+00:00/task_id=merge_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-20T14:50:19.910416+00:00/task_id=merge_data'
[2025-05-20T14:50:26.956+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dimensional_model.merge_data manual__2025-05-20T14:50:19.910416+00:00 [queued]>
[2025-05-20T14:50:26.962+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dimensional_model.merge_data manual__2025-05-20T14:50:19.910416+00:00 [queued]>
[2025-05-20T14:50:26.962+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2025-05-20T14:50:26.973+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): merge_data> on 2025-05-20 14:50:19.910416+00:00
[2025-05-20T14:50:26.977+0000] {standard_task_runner.py:60} INFO - Started process 221 to run task
[2025-05-20T14:50:26.979+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'etl_dimensional_model', 'merge_data', 'manual__2025-05-20T14:50:19.910416+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/etl_load_postgres_dag.py', '--cfg-path', '/tmp/tmp27mx8rw0']
[2025-05-20T14:50:26.981+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask merge_data
[2025-05-20T14:50:27.017+0000] {logging_mixin.py:188} INFO - Changing /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-20T14:50:19.910416+00:00/task_id=merge_data permission to 509
[2025-05-20T14:50:27.017+0000] {logging_mixin.py:188} INFO - Failed to change /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-20T14:50:19.910416+00:00/task_id=merge_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-20T14:50:19.910416+00:00/task_id=merge_data'
[2025-05-20T14:50:27.018+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_dimensional_model.merge_data manual__2025-05-20T14:50:19.910416+00:00 [running]> on host 8ca2b0035139
[2025-05-20T14:50:27.182+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_dimensional_model' AIRFLOW_CTX_TASK_ID='merge_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-20T14:50:19.910416+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-20T14:50:19.910416+00:00'
[2025-05-20T14:50:28.562+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-20T14:50:28.572+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_dimensional_model, task_id=merge_data, execution_date=20250520T145019, start_date=20250520T145026, end_date=20250520T145028
[2025-05-20T14:50:28.595+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-20T14:50:28.612+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
