[2025-05-19T14:24:29.896+0000] {logging_mixin.py:188} INFO - Changing /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-19T14:24:22.026730+00:00/task_id=merge_data permission to 509
[2025-05-19T14:24:29.896+0000] {logging_mixin.py:188} INFO - Failed to change /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-19T14:24:22.026730+00:00/task_id=merge_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-19T14:24:22.026730+00:00/task_id=merge_data'
[2025-05-19T14:24:29.916+0000] {logging_mixin.py:188} INFO - Changing /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-19T14:24:22.026730+00:00/task_id=merge_data permission to 509
[2025-05-19T14:24:29.917+0000] {logging_mixin.py:188} INFO - Failed to change /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-19T14:24:22.026730+00:00/task_id=merge_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-19T14:24:22.026730+00:00/task_id=merge_data'
[2025-05-19T14:24:29.945+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dimensional_model.merge_data manual__2025-05-19T14:24:22.026730+00:00 [queued]>
[2025-05-19T14:24:29.951+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dimensional_model.merge_data manual__2025-05-19T14:24:22.026730+00:00 [queued]>
[2025-05-19T14:24:29.951+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2025-05-19T14:24:29.961+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): merge_data> on 2025-05-19 14:24:22.026730+00:00
[2025-05-19T14:24:29.966+0000] {standard_task_runner.py:60} INFO - Started process 243 to run task
[2025-05-19T14:24:29.968+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'etl_dimensional_model', 'merge_data', 'manual__2025-05-19T14:24:22.026730+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/etl_load_postgres_dag.py', '--cfg-path', '/tmp/tmppjh0pcic']
[2025-05-19T14:24:29.969+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask merge_data
[2025-05-19T14:24:30.003+0000] {logging_mixin.py:188} INFO - Changing /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-19T14:24:22.026730+00:00/task_id=merge_data permission to 509
[2025-05-19T14:24:30.003+0000] {logging_mixin.py:188} INFO - Failed to change /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-19T14:24:22.026730+00:00/task_id=merge_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-19T14:24:22.026730+00:00/task_id=merge_data'
[2025-05-19T14:24:30.005+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_dimensional_model.merge_data manual__2025-05-19T14:24:22.026730+00:00 [running]> on host ca99e8907df9
[2025-05-19T14:24:30.176+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_dimensional_model' AIRFLOW_CTX_TASK_ID='merge_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-19T14:24:22.026730+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-19T14:24:22.026730+00:00'
[2025-05-19T14:24:31.475+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-19T14:24:31.483+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_dimensional_model, task_id=merge_data, execution_date=20250519T142422, start_date=20250519T142429, end_date=20250519T142431
[2025-05-19T14:24:31.542+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-19T14:24:31.559+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
