[2025-05-21T22:24:45.954+0000] {logging_mixin.py:154} INFO - Changing /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-21T22:24:36.089852+00:00/task_id=merge_data permission to 509
[2025-05-21T22:24:45.954+0000] {logging_mixin.py:154} INFO - Failed to change /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-21T22:24:36.089852+00:00/task_id=merge_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-21T22:24:36.089852+00:00/task_id=merge_data'
[2025-05-21T22:24:45.974+0000] {logging_mixin.py:154} INFO - Changing /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-21T22:24:36.089852+00:00/task_id=merge_data permission to 509
[2025-05-21T22:24:45.975+0000] {logging_mixin.py:154} INFO - Failed to change /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-21T22:24:36.089852+00:00/task_id=merge_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-21T22:24:36.089852+00:00/task_id=merge_data'
[2025-05-21T22:24:46.002+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dimensional_model.merge_data manual__2025-05-21T22:24:36.089852+00:00 [queued]>
[2025-05-21T22:24:46.007+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dimensional_model.merge_data manual__2025-05-21T22:24:36.089852+00:00 [queued]>
[2025-05-21T22:24:46.008+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-05-21T22:24:46.017+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): merge_data> on 2025-05-21 22:24:36.089852+00:00
[2025-05-21T22:24:46.022+0000] {standard_task_runner.py:57} INFO - Started process 204 to run task
[2025-05-21T22:24:46.024+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_dimensional_model', 'merge_data', 'manual__2025-05-21T22:24:36.089852+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/etl_load_postgres_dag.py', '--cfg-path', '/tmp/tmphgs0mbql']
[2025-05-21T22:24:46.025+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask merge_data
[2025-05-21T22:24:46.059+0000] {logging_mixin.py:154} INFO - Changing /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-21T22:24:36.089852+00:00/task_id=merge_data permission to 509
[2025-05-21T22:24:46.059+0000] {logging_mixin.py:154} INFO - Failed to change /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-21T22:24:36.089852+00:00/task_id=merge_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-21T22:24:36.089852+00:00/task_id=merge_data'
[2025-05-21T22:24:46.060+0000] {task_command.py:416} INFO - Running <TaskInstance: etl_dimensional_model.merge_data manual__2025-05-21T22:24:36.089852+00:00 [running]> on host 55c1c6b5908a
[2025-05-21T22:24:46.119+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_dimensional_model' AIRFLOW_CTX_TASK_ID='merge_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-21T22:24:36.089852+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-21T22:24:36.089852+00:00'
[2025-05-21T22:24:47.391+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-05-21T22:24:47.399+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_dimensional_model, task_id=merge_data, execution_date=20250521T222436, start_date=20250521T222446, end_date=20250521T222447
[2025-05-21T22:24:47.438+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-21T22:24:47.460+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
