[2025-05-21T14:20:29.168+0000] {logging_mixin.py:188} INFO - Changing /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-21T14:20:18.671924+00:00/task_id=merge_data permission to 509
[2025-05-21T14:20:29.169+0000] {logging_mixin.py:188} INFO - Failed to change /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-21T14:20:18.671924+00:00/task_id=merge_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-21T14:20:18.671924+00:00/task_id=merge_data'
[2025-05-21T14:20:29.198+0000] {logging_mixin.py:188} INFO - Changing /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-21T14:20:18.671924+00:00/task_id=merge_data permission to 509
[2025-05-21T14:20:29.198+0000] {logging_mixin.py:188} INFO - Failed to change /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-21T14:20:18.671924+00:00/task_id=merge_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-21T14:20:18.671924+00:00/task_id=merge_data'
[2025-05-21T14:20:29.227+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dimensional_model.merge_data manual__2025-05-21T14:20:18.671924+00:00 [queued]>
[2025-05-21T14:20:29.233+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dimensional_model.merge_data manual__2025-05-21T14:20:18.671924+00:00 [queued]>
[2025-05-21T14:20:29.234+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2025-05-21T14:20:29.244+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): merge_data> on 2025-05-21 14:20:18.671924+00:00
[2025-05-21T14:20:29.250+0000] {standard_task_runner.py:60} INFO - Started process 239 to run task
[2025-05-21T14:20:29.252+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'etl_dimensional_model', 'merge_data', 'manual__2025-05-21T14:20:18.671924+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/etl_load_postgres_dag.py', '--cfg-path', '/tmp/tmpwa7o_sfw']
[2025-05-21T14:20:29.253+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask merge_data
[2025-05-21T14:20:29.287+0000] {logging_mixin.py:188} INFO - Changing /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-21T14:20:18.671924+00:00/task_id=merge_data permission to 509
[2025-05-21T14:20:29.287+0000] {logging_mixin.py:188} INFO - Failed to change /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-21T14:20:18.671924+00:00/task_id=merge_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-21T14:20:18.671924+00:00/task_id=merge_data'
[2025-05-21T14:20:29.289+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_dimensional_model.merge_data manual__2025-05-21T14:20:18.671924+00:00 [running]> on host 66fd713a3b79
[2025-05-21T14:20:29.444+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_dimensional_model' AIRFLOW_CTX_TASK_ID='merge_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-21T14:20:18.671924+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-21T14:20:18.671924+00:00'
[2025-05-21T14:20:30.761+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-21T14:20:30.770+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_dimensional_model, task_id=merge_data, execution_date=20250521T142018, start_date=20250521T142029, end_date=20250521T142030
[2025-05-21T14:20:30.827+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-21T14:20:30.844+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
