[2025-05-20T21:01:02.814+0000] {logging_mixin.py:188} INFO - Changing /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-20T21:00:55.262061+00:00/task_id=merge_data permission to 509
[2025-05-20T21:01:02.814+0000] {logging_mixin.py:188} INFO - Failed to change /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-20T21:00:55.262061+00:00/task_id=merge_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-20T21:00:55.262061+00:00/task_id=merge_data'
[2025-05-20T21:01:02.840+0000] {logging_mixin.py:188} INFO - Changing /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-20T21:00:55.262061+00:00/task_id=merge_data permission to 509
[2025-05-20T21:01:02.841+0000] {logging_mixin.py:188} INFO - Failed to change /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-20T21:00:55.262061+00:00/task_id=merge_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-20T21:00:55.262061+00:00/task_id=merge_data'
[2025-05-20T21:01:02.878+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dimensional_model.merge_data manual__2025-05-20T21:00:55.262061+00:00 [queued]>
[2025-05-20T21:01:02.886+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dimensional_model.merge_data manual__2025-05-20T21:00:55.262061+00:00 [queued]>
[2025-05-20T21:01:02.887+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2025-05-20T21:01:02.900+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): merge_data> on 2025-05-20 21:00:55.262061+00:00
[2025-05-20T21:01:02.906+0000] {standard_task_runner.py:60} INFO - Started process 233 to run task
[2025-05-20T21:01:02.908+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'etl_dimensional_model', 'merge_data', 'manual__2025-05-20T21:00:55.262061+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/etl_load_postgres_dag.py', '--cfg-path', '/tmp/tmppfoaydkj']
[2025-05-20T21:01:02.910+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask merge_data
[2025-05-20T21:01:02.955+0000] {logging_mixin.py:188} INFO - Changing /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-20T21:00:55.262061+00:00/task_id=merge_data permission to 509
[2025-05-20T21:01:02.956+0000] {logging_mixin.py:188} INFO - Failed to change /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-20T21:00:55.262061+00:00/task_id=merge_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-20T21:00:55.262061+00:00/task_id=merge_data'
[2025-05-20T21:01:02.957+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_dimensional_model.merge_data manual__2025-05-20T21:00:55.262061+00:00 [running]> on host 0bb6b1ca159b
[2025-05-20T21:01:03.159+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_dimensional_model' AIRFLOW_CTX_TASK_ID='merge_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-20T21:00:55.262061+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-20T21:00:55.262061+00:00'
[2025-05-20T21:01:04.888+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-20T21:01:04.899+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_dimensional_model, task_id=merge_data, execution_date=20250520T210055, start_date=20250520T210102, end_date=20250520T210104
[2025-05-20T21:01:04.924+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-20T21:01:04.944+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
