[2025-05-21T23:22:20.492+0000] {logging_mixin.py:154} INFO - Changing /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-21T23:22:12.937585+00:00/task_id=merge_data permission to 509
[2025-05-21T23:22:20.493+0000] {logging_mixin.py:154} INFO - Failed to change /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-21T23:22:12.937585+00:00/task_id=merge_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-21T23:22:12.937585+00:00/task_id=merge_data'
[2025-05-21T23:22:20.516+0000] {logging_mixin.py:154} INFO - Changing /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-21T23:22:12.937585+00:00/task_id=merge_data permission to 509
[2025-05-21T23:22:20.517+0000] {logging_mixin.py:154} INFO - Failed to change /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-21T23:22:12.937585+00:00/task_id=merge_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-21T23:22:12.937585+00:00/task_id=merge_data'
[2025-05-21T23:22:20.549+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dimensional_model.merge_data manual__2025-05-21T23:22:12.937585+00:00 [queued]>
[2025-05-21T23:22:20.556+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dimensional_model.merge_data manual__2025-05-21T23:22:12.937585+00:00 [queued]>
[2025-05-21T23:22:20.557+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-05-21T23:22:20.567+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): merge_data> on 2025-05-21 23:22:12.937585+00:00
[2025-05-21T23:22:20.572+0000] {standard_task_runner.py:57} INFO - Started process 300 to run task
[2025-05-21T23:22:20.575+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'etl_dimensional_model', 'merge_data', 'manual__2025-05-21T23:22:12.937585+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/etl_load_postgres_dag.py', '--cfg-path', '/tmp/tmpzcamr__h']
[2025-05-21T23:22:20.576+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask merge_data
[2025-05-21T23:22:20.617+0000] {logging_mixin.py:154} INFO - Changing /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-21T23:22:12.937585+00:00/task_id=merge_data permission to 509
[2025-05-21T23:22:20.618+0000] {logging_mixin.py:154} INFO - Failed to change /opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-21T23:22:12.937585+00:00/task_id=merge_data permission to 509: [Errno 1] Operation not permitted: '/opt/airflow/logs/dag_id=etl_dimensional_model/run_id=manual__2025-05-21T23:22:12.937585+00:00/task_id=merge_data'
[2025-05-21T23:22:20.619+0000] {task_command.py:416} INFO - Running <TaskInstance: etl_dimensional_model.merge_data manual__2025-05-21T23:22:12.937585+00:00 [running]> on host 30ee4978a6d9
[2025-05-21T23:22:20.688+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_dimensional_model' AIRFLOW_CTX_TASK_ID='merge_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-21T23:22:12.937585+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-21T23:22:12.937585+00:00'
[2025-05-21T23:22:22.081+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-05-21T23:22:22.091+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_dimensional_model, task_id=merge_data, execution_date=20250521T232212, start_date=20250521T232220, end_date=20250521T232222
[2025-05-21T23:22:22.109+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-21T23:22:22.127+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
